<?php
include('../_config.php');

header('Content-type: application/xml');

echo "<?xml version='1.0' encoding='UTF-8'?>"."\n";
echo "<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>"."\n";  ?>
<url>
<loc><?=$websiteAbsoluteUrl?>/</loc>
<changefreq>daily</changefreq>
<priority>1.0000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/home</loc>
<changefreq>daily</changefreq>
<priority>1.0000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/new-season</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/type/movies</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/popular</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/drama</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/school</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/shounen+ai</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/slice+of+life</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/adventure</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/game</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/harem</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/martial+arts</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/seinen</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/action</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/comedy</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/fantasy</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/sci+fi</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/shounen</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/mystery</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/magic</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/mecha</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/demons</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/military</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/shoujo</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/romance</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/ecchi</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/super+power</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/supernatural</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/parody</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/sports</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/music</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/horror</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/psychological</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/historical</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/dementia</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/police</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/thriller</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/shoujo+ai</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/space</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/samurai</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/kids</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/yaoi</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/josei</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/vampire</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/cars</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/yuri</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/genre/dub</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/fall-2021-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/spring-2021-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/summer-2021-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/winter-2021-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/fall-2020-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/spring-2020-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/summer-2020-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/winter-2020-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/fall-2019-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/spring-2019-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/summer-2019-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/winter-2019-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/fall-2018-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/spring-2018-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/summer-2018-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/winter-2018-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/fall-2017-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/spring-2017-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/summer-2017-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/winter-2017-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/fall-2016-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/spring-2016-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/summer-2016-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/winter-2016-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/fall-2015-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/spring-2015-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/summer-2015-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/winter-2015-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/fall-2014-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/spring-2014-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/summer-2014-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/sub-category/winter-2014-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/terms</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/dmca</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/A</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/B</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/C</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/D</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/E</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/F</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/G</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/H</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/I</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/J</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/K</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/L</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/M</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/N</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/O</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/P</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/Q</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/R</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/S</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/T</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/U</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/V</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/W</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/X</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/Y</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/az-list/Z</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/type/tv-series</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/status/ongoing</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc><?=$websiteAbsoluteUrl?>/status/completed</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
</urlset>